In [1]:
import numpy as np

In [7]:
#Crear vector
vector = np.array(range(3,28))
vector

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 21, 22, 23, 24, 25, 26, 27])

In [4]:
arreglo = np.array([0,1,2,3,4,0,1,2,3,4])
arreglo

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

In [5]:
np.sort(arreglo)

array([0, 0, 1, 1, 2, 2, 3, 3, 4, 4])

In [11]:
arreglo

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4])