In [15]:
##Numpy
import numpy as np

In [11]:
##matrices

matriz = np.arange(2,15,2)
matriz

array([ 2,  4,  6,  8, 10, 12, 14])

In [10]:
matriz2 = np.arange(3,10,1)
matriz2

array([3, 4, 5, 6, 7, 8, 9])

In [13]:
matrizdoble = np.array([matriz,matriz2])
matrizdoble

array([[ 2,  4,  6,  8, 10, 12, 14],
       [ 3,  4,  5,  6,  7,  8,  9]])

In [16]:
h=np.reshape(np.array(range(1,26)),(5,5))
h

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

# Actividad lunes 5 septiembre(clase 6)

In [17]:
actMatriz=np.reshape(np.array(range(0,9)),(3,3))
actMatriz

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [19]:
actIdentity=np.identity(6)
actIdentity

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [1]:
##condicionantes y iperaciones clase 7
#el doble de mi edad es 24, cuantos años tengo?
x = 24/2
x

12.0

# Actividades 6 septiembre(Clase7)

In [14]:
#un tercio de la edad de mi hermana la diminuyo en 15, tengo 6 años, que edad tenia?
#x-15 = 6
x = 6
y = (15+x)*3
#quien es mayor?
x_mayor = x > y
if(x_mayor):
    print("x es mayor")
else:
    print("y es mayor")

y es mayor


In [16]:
#Mascara
a=np.array([1,2,3,4,5,6,7])
a

array([1, 2, 3, 4, 5, 6, 7])

In [17]:
mascara = a>3
mascara

array([False, False, False,  True,  True,  True,  True])

In [26]:
#condicionantes y ciclos
a=1
if a==3:
    a=a*3
    print(a)
elif a>10:
    a%=2
    print(a)
else:
    print(a)


1


In [ ]:
animales = ["animal1","animal2","animal3","animal4","animal5","animal6",]


In [39]:
#actividad 8
#Operaciones Edad
edades = [10,20,30,15,18,17,22,21]
mayoria = int(input("Escribe la mayoria de edad, numero entero"))
for edad in edades:
    if(edad>=mayoria):
        print("Con", edad, "años, eres MAYOR de edad")
    else:
        print("Con", edad, "años, eres menor de edad")

Escribe la mayoria de edad, numero entero22
Con 10 años, eres menor de edad
Con 20 años, eres menor de edad
Con 30 años, eres MAYOR de edad
Con 15 años, eres menor de edad
Con 18 años, eres menor de edad
Con 17 años, eres menor de edad
Con 22 años, eres MAYOR de edad
Con 21 años, eres menor de edad


In [45]:
#actividad 9
#cual numero es menor
num1 = int(input("Escribe el numero1, numero entero"))
num2 = int(input("Escribe el numero2, numero entero"))
if(num1>num2):
    print(num2, "es menor")
elif(num2>num1):
    print(num1, "es menor")
else:
    print("los dos numeros son iguales:", num1, "y",num2)

Escribe el numero1, numero entero7
Escribe el numero2, numero entero6
6 es menor
