In [3]:
##Numpy
import numpy as np

In [11]:
##matrices

matriz = np.arange(2,15,2)
matriz

array([ 2,  4,  6,  8, 10, 12, 14])

In [10]:
matriz2 = np.arange(3,10,1)
matriz2

array([3, 4, 5, 6, 7, 8, 9])

In [13]:
matrizdoble = np.array([matriz,matriz2])
matrizdoble

array([[ 2,  4,  6,  8, 10, 12, 14],
       [ 3,  4,  5,  6,  7,  8,  9]])

In [16]:
h=np.reshape(np.array(range(1,26)),(5,5))
h

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

# Actividad lunes 5 septiembre(clase 6)

In [17]:
actMatriz=np.reshape(np.array(range(0,9)),(3,3))
actMatriz

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [19]:
actIdentity=np.identity(6)
actIdentity

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])